### PR TITLE
Runtime 23.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Looks like gstreamer is locked `error: failed to select a version for the requirement `gstreamer = "^0.16"` (locked to 0.16.5)`

**Comment by bbhtt** [comment]
Looks like scribl.sh was never used. The command points to the binary and not the script. Upstream also removed it...

**Comment by bbhtt** [comment]
Runs

**Review by jneem — APPROVED** [review]
Thanks!

**Pull request merged**
